[package]
name = "activity_tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
serde_json = "1.0.143"
serde = { version = "1.0", features = ["derive"]}
thiserror = "2.0.16"
